#!/bin/zsh

set -e

cd ${0:A:h}

if [[ ! -f .env ]]; then
    echo "replacement info missed"
    return
fi
export $(grep -v '^#' .env | xargs)

ssh_conn="unraid.home"
src="/boot/config/plugins/dockerMan/templates-user"
from=${ssh_conn}:${src}/*
echo from: ${from}
to=$(pwd)/templates/
echo to: ${to}

if [[ ! -d ${to} ]];then
    mkdir ${to}
fi

rsync -avzP --chmod=Du=rwx,Dgo=rx,Fu=rw,Fgo=r "${from}" "${to}"

replacement=(${(s/|/)replacement})
for item in "${replacement[@]}"
do
    sed -i '' "s|$item</Config>|******</Config>|g" templates/*.xml
done

rg -i --pcre2 '^\s*<(?!(icon>|repository>|registry>)).*(991645|token|password)(?:(?!(\*\*\*\*\*\*|/>)).)*$'

rg -i --pcre2 '^\s*<(?!(icon>|repository>|registry>)).*(991645|token|password)(?:(?!(\*\*\*\*\*\*|/>)).)*$' | rg '>.*<'