#!/bin/zsh

set -ex

if [[ ! -f .env ]]; then
    echo "connection info missed"
    return
fi
export $(grep -v '^#' .env | xargs)

echo smb: ${smb}
src=/Volumes/$(basename ${smb})/plugins/dockerMan/templates-user
echo src: ${src}
if [[ ! -d ${src} ]]; then
    echo "mount smb share ${src}"
    open ${smb}
    sleep 10
    if [[ ! -d ${src} ]]; then
        err="[mount] ${smb} mount failed"
        echo $err
        return
    fi
fi

from=${src}/*
echo from: ${from}
to=$(pwd)/templates/
echo to: ${to}

if [[ ! -d ${to} ]];then
    mkdir ${to}
fi

cp ${src}/* ${to}
chmod 644 ${to}*

replacement=(${(s/|/)replacement})
for item in "${replacement[@]}"
do
    sed -i '' "s|$item</Config>|******</Config>|g" templates/*.xml
done

rg --pcre2 '^\s*<(?!(Icon>|Repository>|Registry>)).*(991645|token|TOKEN|Token|PASSWORD|Password|password)(?:(?!(\*\*\*\*\*\*|/>)).)*$'

rg --pcre2 '^\s*<(?!(Icon>|Repository>|Registry>)).*(991645|token|TOKEN|Token|PASSWORD|Password|password)(?:(?!(\*\*\*\*\*\*|/>)).)*$' | rg '>.*<'